# Deploy configuration for Perron
# Requires Beam Up (`bundle add beam_up`)
# See also: https://perron.railsdesigner.com/docs/deploy/

# Uncomment and configure your provider:
# provider: netlify

# netlify:
#   api_token: your_token_here
#   site_id: your_site_id

before_actions:
  - RAILS_ENV=production bundle exec rails perron:build
after_actions:
  - bundle exec rails perron:clobber
